-- Generado por Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   en:        2023-03-21 17:42:18 CET
--   sitio:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE ALUMNO 
    (
     Nombre CHAR NOT NULL , 
     Apellidos CHAR NOT NULL , 
     CorreoElectronico VARCHAR , 
     País CHAR , 
     Télefono NUMERIC (12) , 
     Edad VARCHAR NOT NULL , 
     ALUMNO_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE ALUMNO ADD CONSTRAINT ALUMNO_PK PRIMARY KEY CLUSTERED (ALUMNO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Avanzado 
    (
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Avanzado ADD CONSTRAINT Avanzado_PK PRIMARY KEY CLUSTERED (NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CLASE_Backup 
    (
     Descripcion VARCHAR , 
     Duracion NUMERIC (28) , 
     Plataforma VARCHAR , 
     Tema VARCHAR , 
     CLASE_Backup_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     TUTOR_TUTOR_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE CLASE_Backup ADD CONSTRAINT CLASE_Backup_PK PRIMARY KEY CLUSTERED (CLASE_Backup_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DIRECCION 
    (
     Calle VARCHAR NOT NULL , 
     Numero NUMERIC (28) NOT NULL , 
     CodigoPostal NUMERIC (5) NOT NULL , 
     Localidad VARCHAR NOT NULL , 
     Provincia CHAR NOT NULL , 
     DIRECCION_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     TUTOR_TUTOR_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE DIRECCION ADD CONSTRAINT DIRECCION_PK PRIMARY KEY CLUSTERED (DIRECCION_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FACTURA 
    (
     IVA NUMERIC (3) , 
     TotalTutoria MONEY , 
     BonoDescuento MONEY , 
     ImporteTotal MONEY , 
     RESERVA_RESERVA_ID NUMERIC (28) NOT NULL 
    )
GO

CREATE TABLE FORMACIÓN 
    (
     Universidad CHAR , 
     Titulo CHAR , 
     Año DATE , 
     FORMACIÓN_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE FORMACIÓN ADD CONSTRAINT FORMACIÓN_PK PRIMARY KEY CLUSTERED (FORMACIÓN_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FRANJA_HORARIA 
    (
     NombreFranjaHoraria VARCHAR NOT NULL , 
     DiferenciaTiempo NUMERIC (28) NOT NULL , 
     FRANJA_HORARIA_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE FRANJA_HORARIA ADD CONSTRAINT FRANJA_HORARIA_PK PRIMARY KEY CLUSTERED (FRANJA_HORARIA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE IDIOMA 
    (
     IdiomaNativo CHAR , 
     IdiomaEnseñanza CHAR , 
     IdiomaNivel CHAR , 
     IDIOMA_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE IDIOMA ADD CONSTRAINT IDIOMA_PK PRIMARY KEY CLUSTERED (IDIOMA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Intermedio 
    (
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Intermedio ADD CONSTRAINT Intermedio_PK PRIMARY KEY CLUSTERED (NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE NIVEL_ESTUDIANTE 
    (
     NIVEL_ESTUDIANTE_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     Descripcion CHAR 
    )
GO

ALTER TABLE NIVEL_ESTUDIANTE ADD CONSTRAINT NIVEL_ESTUDIANTE_PK PRIMARY KEY CLUSTERED (NIVEL_ESTUDIANTE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PAGO 
    (
     PAGO_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     TipoPago VARCHAR 
    )
GO

ALTER TABLE PAGO ADD CONSTRAINT PAGO_PK PRIMARY KEY CLUSTERED (PAGO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PAY_PAL 
    (
     PAGO_PAGO_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE PAY_PAL ADD CONSTRAINT PAY_PAL_PK PRIMARY KEY CLUSTERED (PAGO_PAGO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Principiante 
    (
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Principiante ADD CONSTRAINT Principiante_PK PRIMARY KEY CLUSTERED (NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE RESEÑA 
    (
     Descripcion CHAR , 
     Fecha DATE NOT NULL , 
     RESEÑA_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION 
    )
GO

ALTER TABLE RESEÑA ADD CONSTRAINT RESEÑA_PK PRIMARY KEY CLUSTERED (RESEÑA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE RESERVA 
    (
     Descripcion VARCHAR , 
     RESERVA_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     TUTOR_TUTOR_ID NUMERIC (28) NOT NULL , 
     PAGO_PAGO_ID NUMERIC (28) NOT NULL , 
     DIRECCION_DIRECCION_ID NUMERIC (28) NOT NULL , 
     ALUMNO_ALUMNO_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PK PRIMARY KEY CLUSTERED (RESERVA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SUSCRIPCION 
    (
     Descripcion VARCHAR , 
     FechaSuscripcion DATE NOT NULL , 
     FechaFin DATE NOT NULL , 
     ALUMNO_ALUMNO_ID NUMERIC (28) NOT NULL , 
     CLASE_Backup_CLASE_Backup_ID NUMERIC (28) NOT NULL 
    )
GO

CREATE TABLE Tarjeta_Credito 
    (
     PAGO_PAGO_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Tarjeta_Credito ADD CONSTRAINT Tarjeta_Credito_PK PRIMARY KEY CLUSTERED (PAGO_PAGO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TUTOR 
    (
     Nombre CHAR NOT NULL , 
     Apellidos CHAR NOT NULL , 
     CorreoElectronico VARCHAR NOT NULL , 
     FechaNacimiento DATE NOT NULL , 
     MaximaDistanciaDesplazamiento NUMERIC (28) NOT NULL , 
     CosteDesplazamiento NUMERIC (28) NOT NULL , 
     ImagenPerfil VARCHAR NOT NULL , 
     DesdeCuandoEsProfesora DATE NOT NULL , 
     TUTOR_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     FRANJA_HORARIA_FRANJA_HORARIA_ID NUMERIC (28) NOT NULL , 
     IDIOMA_IDIOMA_ID NUMERIC (28) NOT NULL , 
     FORMACIÓN_FORMACIÓN_ID NUMERIC (28) NOT NULL , 
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID NUMERIC (28) NOT NULL , 
     RESEÑA_RESEÑA_ID NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE TUTOR ADD CONSTRAINT TUTOR_PK PRIMARY KEY CLUSTERED (TUTOR_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Avanzado 
    ADD CONSTRAINT Avanzado_NIVEL_ESTUDIANTE_FK FOREIGN KEY 
    ( 
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID
    ) 
    REFERENCES NIVEL_ESTUDIANTE 
    ( 
     NIVEL_ESTUDIANTE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CLASE_Backup 
    ADD CONSTRAINT CLASE_Backup_TUTOR_FK FOREIGN KEY 
    ( 
     TUTOR_TUTOR_ID
    ) 
    REFERENCES TUTOR 
    ( 
     TUTOR_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DIRECCION 
    ADD CONSTRAINT DIRECCION_TUTOR_FK FOREIGN KEY 
    ( 
     TUTOR_TUTOR_ID
    ) 
    REFERENCES TUTOR 
    ( 
     TUTOR_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FACTURA 
    ADD CONSTRAINT FACTURA_RESERVA_FK FOREIGN KEY 
    ( 
     RESERVA_RESERVA_ID
    ) 
    REFERENCES RESERVA 
    ( 
     RESERVA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Intermedio 
    ADD CONSTRAINT Intermedio_NIVEL_ESTUDIANTE_FK FOREIGN KEY 
    ( 
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID
    ) 
    REFERENCES NIVEL_ESTUDIANTE 
    ( 
     NIVEL_ESTUDIANTE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PAY_PAL 
    ADD CONSTRAINT PAY_PAL_PAGO_FK FOREIGN KEY 
    ( 
     PAGO_PAGO_ID
    ) 
    REFERENCES PAGO 
    ( 
     PAGO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Principiante 
    ADD CONSTRAINT Principiante_NIVEL_ESTUDIANTE_FK FOREIGN KEY 
    ( 
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID
    ) 
    REFERENCES NIVEL_ESTUDIANTE 
    ( 
     NIVEL_ESTUDIANTE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RESERVA 
    ADD CONSTRAINT RESERVA_ALUMNO_FK FOREIGN KEY 
    ( 
     ALUMNO_ALUMNO_ID
    ) 
    REFERENCES ALUMNO 
    ( 
     ALUMNO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RESERVA 
    ADD CONSTRAINT RESERVA_DIRECCION_FK FOREIGN KEY 
    ( 
     DIRECCION_DIRECCION_ID
    ) 
    REFERENCES DIRECCION 
    ( 
     DIRECCION_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RESERVA 
    ADD CONSTRAINT RESERVA_PAGO_FK FOREIGN KEY 
    ( 
     PAGO_PAGO_ID
    ) 
    REFERENCES PAGO 
    ( 
     PAGO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RESERVA 
    ADD CONSTRAINT RESERVA_TUTOR_FK FOREIGN KEY 
    ( 
     TUTOR_TUTOR_ID
    ) 
    REFERENCES TUTOR 
    ( 
     TUTOR_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUSCRIPCION 
    ADD CONSTRAINT SUSCRIPCION_ALUMNO_FK FOREIGN KEY 
    ( 
     ALUMNO_ALUMNO_ID
    ) 
    REFERENCES ALUMNO 
    ( 
     ALUMNO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SUSCRIPCION 
    ADD CONSTRAINT SUSCRIPCION_CLASE_Backup_FK FOREIGN KEY 
    ( 
     CLASE_Backup_CLASE_Backup_ID
    ) 
    REFERENCES CLASE_Backup 
    ( 
     CLASE_Backup_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Tarjeta_Credito 
    ADD CONSTRAINT Tarjeta_Credito_PAGO_FK FOREIGN KEY 
    ( 
     PAGO_PAGO_ID
    ) 
    REFERENCES PAGO 
    ( 
     PAGO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TUTOR 
    ADD CONSTRAINT TUTOR_FORMACIÓN_FK FOREIGN KEY 
    ( 
     FORMACIÓN_FORMACIÓN_ID
    ) 
    REFERENCES FORMACIÓN 
    ( 
     FORMACIÓN_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TUTOR 
    ADD CONSTRAINT TUTOR_FRANJA_HORARIA_FK FOREIGN KEY 
    ( 
     FRANJA_HORARIA_FRANJA_HORARIA_ID
    ) 
    REFERENCES FRANJA_HORARIA 
    ( 
     FRANJA_HORARIA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TUTOR 
    ADD CONSTRAINT TUTOR_IDIOMA_FK FOREIGN KEY 
    ( 
     IDIOMA_IDIOMA_ID
    ) 
    REFERENCES IDIOMA 
    ( 
     IDIOMA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TUTOR 
    ADD CONSTRAINT TUTOR_NIVEL_ESTUDIANTE_FK FOREIGN KEY 
    ( 
     NIVEL_ESTUDIANTE_NIVEL_ESTUDIANTE_ID
    ) 
    REFERENCES NIVEL_ESTUDIANTE 
    ( 
     NIVEL_ESTUDIANTE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TUTOR 
    ADD CONSTRAINT TUTOR_RESEÑA_FK FOREIGN KEY 
    ( 
     RESEÑA_RESEÑA_ID
    ) 
    REFERENCES RESEÑA 
    ( 
     RESEÑA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             0
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
